#!/bin/bash
mkdir archives
mkdir logs
mkdir diffs
mkdir public_html
mkdir -p clean/plugins
mkdir -p clean/themes
mkdir -p security_analysis/infected-source
mkdir -p security_analysis/infected-html
mkdir -p security_analysis/notes
echo "Security analysis notes" > security_analysis/notes/notes
echo "Vulnerability RegExps" > security_analysis/notes/vulnerability.txt
vim _creds
echo "\n\n\n" > creds
echo >> "\n ----- Credentials -----\n\n"
gpg -d _creds >> creds
echo >> "\n --- end Credentials ---\n\n"

rm _creds

printf "\n ----- Credentials -----\n"
cat creds
printf "\n --- end Credentials ---\n\n"

# cp regexes to this dir

